### PR TITLE
pretty can now be specified as part of .tag and .startTag

### PR DESCRIPTION
**Pull request by dcramer**
I added pretty to the queue stack and isPretty is now used everywhere as a "default" -- which defaults to self._pretty or last element in stack's pretty value

### CODE REVIEW

**Comment by dcramer** [comment]
Actually this wasnt fully fleshed out, still seeing some weird indentation.

**Comment by roskakori** [comment]
Is it ok for you if I discard this pull and wait for your fix?
It's definitely a feature much appreciated.

**Comment by dcramer** [comment]
Ya you can discard -- its almost working, theres just some odd behavior with indentation im trying to understand

**Comment by roskakori** [comment]
Ok, discarded.

**Pull request closed without merging**
